services:
  app:
    build: .
    container_name: fraud_analysis_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  web:
    image: nginx:stable
    container_name: fraud_analysis_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
